---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conformance-output-data-1-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: conformance-tests-1-1
spec:
  backoffLimit: 0
  template:
    spec:
      initContainers:
      - name: prep-1-1
        image: alpine:3.10
        command: ["chmod", "777", "/output"]
        volumeMounts:
        - mountPath: /output
          name: conformance-output-data-1-1
      containers:
      - name: tests-1-1
        image: calrissian:conformance
        workingDir: "/conformance/cwl-v1.1-1.1.0"
        command: ["./run_test.sh"]
        args:
        - "RUNNER=calrissian"
        - "--verbose"
        - "EXTRA=--max-ram 8G --max-cores 4 --default-container debian:stretch-slim"
        env:
        - name: CALRISSIAN_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TMPDIR
          value: "/output"
        volumeMounts:
        - mountPath: /conformance
          name: conformance-test-data-1-1
          readOnly: true
        - mountPath: /output
          name: conformance-output-data-1-1
      restartPolicy: Never
      volumes:
      - name: conformance-test-data-1-1
        persistentVolumeClaim:
          claimName: conformance-test-data-1-1
          readOnly: true
      - name: conformance-output-data-1-1
        persistentVolumeClaim:
          claimName: conformance-output-data-1-1
