apiVersion: batch/v1
kind: Job
metadata:
  name: conformance-tests-1-2-1
spec:
  backoffLimit: 0
  template:
    spec:
      initContainers:
      - name: prep-1-2-1
        image: alpine:3.10
        command: ["chmod", "777", "/output"]
        volumeMounts:
        - mountPath: /output
          name: conformance-test-output
      containers:
      - name: tests-1-2-1
        imagePullPolicy: IfNotPresent
        image: conformance:latest
        workingDir: "/conformance/cwl-v1.2-1.2.1_proposed"
        command: ["cwltest"]
        args:
        - "--test"
        - "/conformance/cwl-v1.2-1.2.1_proposed/conformance_tests.yaml"
        - "--tool"
        - "calrissian"
        - "--badgedir"
        - "/output/badges-1.2.1_proposed"
        - "--verbose"
        - "--"
        - "--max-ram"
        - "8G"
        - "--max-cores"
        - "4"
        - "--default-container"
        - "debian:stretch-slim"
        env:
        - name: CALRISSIAN_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TMPDIR
          value: "/output"
        volumeMounts:
        - mountPath: /conformance
          name: conformance-test-data
          readOnly: true
        - mountPath: /output
          name: conformance-test-output
      restartPolicy: Never
      volumes:
      - name: conformance-test-data
        persistentVolumeClaim:
          claimName: conformance-test-data
          readOnly: true
      - name: conformance-test-output
        persistentVolumeClaim:
          claimName: conformance-test-output
