apiVersion: batch/v1
kind: Job
metadata:
  name: stage-conformance-test-data
spec:
  template:
    spec:
      containers:
      - name: 1-0
        image: alpine:3.10
        command:
        - "sh"
        - "-c"
        - "cd /conformance; wget -q ${CWL_ARCHIVE_BASE}/${CWL_ARCHIVE_FILE}; unzip -q ${CWL_ARCHIVE_FILE}; rm ${CWL_ARCHIVE_FILE}; chmod -R a+rx *; ls -l"
        env:
        - name: CWL_ARCHIVE_BASE
          value: "https://github.com/common-workflow-language/common-workflow-language/archive"
        - name: CWL_ARCHIVE_FILE
          value: "v1.0.2.zip"
        volumeMounts:
        - mountPath: /conformance
          name: conformance-test-data
      - name: 1-1
        image: alpine:3.10
        command:
        - "sh"
        - "-c"
        - "cd /conformance; wget -q ${CWL_ARCHIVE_BASE}/${CWL_ARCHIVE_FILE}; unzip -q ${CWL_ARCHIVE_FILE}; rm ${CWL_ARCHIVE_FILE}; chmod -R a+rx *; ls -l"
        env:
        - name: CWL_ARCHIVE_BASE
          value: "https://github.com/common-workflow-language/cwl-v1.1/archive"
        - name: CWL_ARCHIVE_FILE
          value: "v1.1.0.zip"
        volumeMounts:
        - mountPath: /conformance
          name: conformance-test-data
      - name: 1-2
        image: alpine:3.10
        command:
        - "sh"
        - "-c"
        - "cd /conformance; wget -q ${CWL_ARCHIVE_BASE}/${CWL_ARCHIVE_FILE}; unzip -q ${CWL_ARCHIVE_FILE}; rm ${CWL_ARCHIVE_FILE}; chmod -R a+rx *; ls -l"
        env:
        - name: CWL_ARCHIVE_BASE
          value: "https://github.com/common-workflow-language/cwl-v1.2/archive/refs/tags"
        - name: CWL_ARCHIVE_FILE
          value: "v1.2.0.zip"
        volumeMounts:
        - mountPath: /conformance
          name: conformance-test-data
      - name: 1-2-1
        image: alpine:3.10
        command:
        - "sh"
        - "-c"
        - "cd /conformance; wget -q ${CWL_ARCHIVE_BASE}/${CWL_ARCHIVE_FILE}; unzip -q ${CWL_ARCHIVE_FILE}; rm ${CWL_ARCHIVE_FILE}; chmod -R a+rx *; ls -l"
        env:
        - name: CWL_ARCHIVE_BASE
          value: "https://github.com/common-workflow-language/cwl-v1.2/archive/refs/heads"
        - name: CWL_ARCHIVE_FILE
          value: "1.2.1_proposed.zip"
        volumeMounts:
        - mountPath: /conformance
          name: conformance-test-data
      restartPolicy: Never
      volumes:
      - name: conformance-test-data
        persistentVolumeClaim:
          claimName: conformance-test-data
