---
apiVersion: batch/v1
kind: Job
metadata:
  name: calrissian-revsort-array
spec:
  template:
    spec:
      containers:
      - name: calrissian
        image: calrissian:latest
        command: ["calrissian"]
        args:
          - "--max-ram"
          - "16384"
          - "--max-cores"
          - "8"
          - "--tmpdir-prefix"
          - "/calrissian/tmptmp/"
          - "--tmp-outdir-prefix"
          - "/calrissian/tmpout/"
          - "--outdir"
          - "/calrissian/output-data/"
          - "--usage-report"
          - "/calrissian/output-data/revsort-usage.yaml"
          - "/calrissian/input-data/revsort-array.cwl"
          - "/calrissian/input-data/revsort-array-job.json"
        volumeMounts:
        - mountPath: /calrissian/input-data
          name: calrissian-input-data
        - mountPath: /calrissian/tmpout
          name: calrissian-tmpout
        - mountPath: /calrissian/tmptmp
          name: calrissian-tmp
        - mountPath: /calrissian/output-data
          name: calrissian-output-data
        env:
        - name: CALRISSIAN_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: Never
      volumes:
      - name: calrissian-input-data
        persistentVolumeClaim:
          claimName: calrissian-input-data
      - name: calrissian-tmpout
        persistentVolumeClaim:
          claimName: calrissian-tmpout
      - name: calrissian-tmp
        persistentVolumeClaim:
          claimName: calrissian-tmp
      - name: calrissian-output-data
        persistentVolumeClaim:
          claimName: calrissian-output-data
  backOffLimit: 0
