---
apiVersion: batch/v1
kind: Job
metadata:
  name: calrissian-revsort-array
spec:
  template:
    spec:
      containers:
      - name: calrissian
        # Jobs cannot use ImageStream images directly, so we have to provide the registry/repo variant
        image: docker-registry.default.svc:5000/calrissian/calrissian:latest
        command: ["/bin/bash", "-c"]
        args: ["python -m calrissian.main --tmpdir-prefix /calrissian/tmptmp/ --tmp-outdir-prefix /calrissian/tmpout/ --outdir /calrissian/output-data/ /calrissian/input-data/revsort-array.cwl /calrissian/input-data/revsort-array-job.json"]
        volumeMounts:
        - mountPath: /calrissian/input-data
          name: calrissian-input-data
        - mountPath: /calrissian/tmpout
          name: calrissian-tmpout
        - mountPath: /calrissian/tmptmp
          name: calrissian-tmp
        - mountPath: /calrissian/output-data
          name: calrissian-output-data
        env:
        - name: CALRISSIAN_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: Never
      volumes:
      - name: calrissian-input-data
        persistentVolumeClaim:
          claimName: calrissian-input-data
      - name: calrissian-tmpout
        persistentVolumeClaim:
          claimName: calrissian-tmpout
      - name: calrissian-tmp
        persistentVolumeClaim:
          claimName: calrissian-tmp
      - name: calrissian-output-data
        persistentVolumeClaim:
          claimName: calrissian-output-data
  backOffLimit: 0
