# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build & Tests
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        pip install hatch
    - name: Cache Hatch
      id: cache-hatch
      uses: actions/cache@v3
      with:
        path: /home/runner/.local/share/hatch/env/virtual/
        key: ${{ runner.os }}-hatch
    - name: Build
      run: hatch build
    - name: Test
      run: |
        hatch -e test run nose2 --verbose