name: docs
on:
  push:
    branches:
    - conformance-1.2.1
    paths:
    # Only rebuild website when docs have changed
    - 'README.md'
    - 'docs/**'
    - 'mkdocs.yml'
    - .github/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: mamba-org/provision-with-micromamba@main
      with:
        micromamba-version: '1.2.0'
        environment-file: false
        environment-name: env_docs
        extra-specs: |
          python=3.10
          pip:
          - mkdocs-material
          - mkdocs-jupyter
        channels: conda-forge

    - name: Install project
      run: |
        /home/runner/micromamba-root/envs/env_docs/bin/python setup.py install

    - run: /home/runner/micromamba-root/envs/env_docs/bin/mkdocs gh-deploy --force
