name: docs
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install hatch pdocs mkdocs-material mkdocs-jupyter mkdocs-plantuml-local pydoctor
        hatch build
        pyreverse --all-ancestors --show-builtin --output svg --output-directory ./docs/puml/ --source-roots ./calrissian/ --verbose ./calrissian/
        pydoctor
        mkdocs gh-deploy --force
