name: docs
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
    - run: | 
        pip install mkdocs-material mkdocs-mermaid2-plugin mkdocs-jupyter legacy-cgi pdocs pylint graphviz
        pip install .
        pdocs as_markdown --output_dir ./docs/api/latest --exclude_source --overwrite calrissian
        mkdir -p ./docs/uml/
        pyreverse --all-ancestors --show-builtin --output svg --output-directory ./docs/uml/ --source-roots ./calrissian/ --verbose ./calrissian/
    - run: mkdocs gh-deploy --force
