name: docs
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Conda environment from environment.yml
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: docs/environment.yml
        environment-name: env_docs
        channels: terradue,eoepca,conda-forge
        channel-priority: flexible

    - name: Install project
      run: |
        /home/runner/micromamba-root/envs/env_docs/bin/python setup.py install

    - run: /home/runner/micromamba-root/envs/env_docs/bin/mkdocs gh-deploy --force
