name: docs
on:
  push:
    branches:
    - master
    paths:
    # Only rebuild website when docs have changed
    - 'README.md'
    - 'docs/**'
    - 'mkdocs.yml'
    - .github/**
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install mkdocs-material mkdocs-mermaid2-plugin mkdocs-jupyter legacy-cgi pdocs pylint graphviz
    - run: pip install .
    - run: pdocs as_markdown --output_dir ./docs/api/latest --exclude_source --overwrite calrissian
    - run: mkdir -p ./docs/uml/
    - run: pyreverse --all-ancestors --show-builtin --output svg --output-directory ./docs/uml/ --source-roots ./calrissian/ --verbose ./calrissian/
    - run: mkdocs gh-deploy --force
